GRC="$(which grc)"
if [ "$TERM" != dumb ] && [ -n "$GRC" ]; then
    alias colourify="$GRC -es --colour=auto"
    alias configure='colourify ./configure'
    alias df='colourify df'
    alias docker='colourify docker'
    alias docker-machine='colourify docker-machine'
    alias du='colourify du'
    alias env='colourify env'
    alias gcc='colourify gcc'
    alias g++='colourify g++'
    alias id='colourify id'
    alias lsof='colourify lsof'
    alias stat='colourify stat'
    alias ping='colourify ping'
    alias traceroute='colourify traceroute'
    alias traceroute6='colourify traceroute6'
    alias head='colourify head'
    alias tail='colourify tail'
    alias dig='colourify dig'
    alias mount='colourify mount'
    alias ps='colourify ps'
    alias mtr='colourify mtr'
    alias ifconfig='colourify ifconfig'
    alias whois='colourify whois'
    alias uptime='colourify uptime'
fi
